PRODUCT_COPY_FILES += \
                $(LOCAL_PATH)/rtl8703as_fw:system/etc/firmware/rtl8703as_fw \
                $(LOCAL_PATH)/rtl8703as_config:system/etc/firmware/rtl8703as_config \
                $(LOCAL_PATH)/rtl8703bs_fw:system/etc/firmware/rtl8703bs_fw \
                $(LOCAL_PATH)/rtl8703bs_config:system/etc/firmware/rtl8703bs_config \
                $(LOCAL_PATH)/rtl8723as_fw:system/etc/firmware/rtl8723as_fw \
                $(LOCAL_PATH)/rtl8723as_config:system/etc/firmware/rtl8723as_config \
                $(LOCAL_PATH)/rtl8723bs_fw:system/etc/firmware/rtl8723bs_fw \
                $(LOCAL_PATH)/rtl8723bs_config:system/etc/firmware/rtl8723bs_config \
                $(LOCAL_PATH)/rtl8723bs_VQ0_fw:system/etc/firmware/rtl8723bs_VQ0_fw \
                $(LOCAL_PATH)/rtl8723bs_VQ0_config:system/etc/firmware/rtl8723bs_VQ0_config \
                $(LOCAL_PATH)/rtl8723ds_fw:system/etc/firmware/rtl8723ds_fw \
                $(LOCAL_PATH)/rtl8723ds_config:system/etc/firmware/rtl8723ds_config \
                $(LOCAL_PATH)/rtl8703cs_fw:system/etc/firmware/rtl8703cs_fw \
                $(LOCAL_PATH)/rtl8703cs_config:system/etc/firmware/rtl8703cs_config \
                $(LOCAL_PATH)/rtl8723cs_xx_fw:system/etc/firmware/rtl8723cs_xx_fw \
                $(LOCAL_PATH)/rtl8723cs_xx_config:system/etc/firmware/rtl8723cs_xx_config \
                $(LOCAL_PATH)/rtl8723cs_cg_fw:system/etc/firmware/rtl8723cs_cg_fw \
                $(LOCAL_PATH)/rtl8723cs_cg_config:system/etc/firmware/rtl8723cs_cg_config \
                $(LOCAL_PATH)/rtl8723cs_vf_fw:system/etc/firmware/rtl8723cs_vf_fw \
                $(LOCAL_PATH)/rtl8723cs_vf_config:system/etc/firmware/rtl8723cs_vf_config \
                $(LOCAL_PATH)/rtl8761at_fw:system/etc/firmware/rtl8761at_fw \
                $(LOCAL_PATH)/rtl8761at_config:system/etc/firmware/rtl8761at_config \
                $(LOCAL_PATH)/rtl8821as_fw:system/etc/firmware/rtl8821as_fw   \
                $(LOCAL_PATH)/rtl8821as_config:system/etc/firmware/rtl8821as_config \
                $(LOCAL_PATH)/rtl8821cs_fw:system/etc/firmware/rtl8821cs_fw   \
                $(LOCAL_PATH)/rtl8821cs_config:system/etc/firmware/rtl8821cs_config \
                $(LOCAL_PATH)/rtl8822bs_fw:system/etc/firmware/rtl8822bs_fw   \
                $(LOCAL_PATH)/rtl8822bs_config:system/etc/firmware/rtl8822bs_config \
                $(LOCAL_PATH)/mp_rtl8723a_fw:system/etc/firmware/mp_rtl8723a_fw \
                $(LOCAL_PATH)/mp_rtl8723b_fw:system/etc/firmware/mp_rtl8723b_fw \
                $(LOCAL_PATH)/mp_rtl8761a_fw:system/etc/firmware/mp_rtl8761a_fw \
                $(LOCAL_PATH)/mp_rtl8821a_fw:system/etc/firmware/mp_rtl8821a_fw \

